### PR TITLE
Rename "coin" logos

### PR DESCRIPTION
**Pull request by nylen**
Background: https://github.com/ClassicPress/ClassicPress-v1/issues/174 for the naming convention for our logo files, https://github.com/ClassicPress/ClassicPress-Network/issues/62 for related ongoing work.

Previously the "coin" logo files were named as though the circular coin part was the foreground, on a transparent background.

Let's rename them to have the "feather" be the foreground and the circular coin be the background. While there is a transparent background in the images, it exists only to complete the circular "coin" form, which is the visual background.

This changes the filenames as follows:

| Image | Old Name | New Name |
|--|--|--|
|  | `coin-gradient-on-transparent` | `coin-white-on-gradient` |
|  | `coin-white-on-transparent` | `coin-gradient-on-white` |

File contents have not been changed, only the names.

### CODE REVIEW

**Comment by timbocode** [comment]
Fine. Makes perfect sense to me.

I've also been working on the `file-list.php` MU plugin which I'll have sorted in the next day or two.

**Comment by nylen** [comment]
The files are already renamed here. I'll merge this now, just wanted to get another pair of eyes on it first. There's no need to do anything else other than update your copy of the ClassicPress-Design repo.

I went ahead and added the logo files to the www webserver, you can use `wp-content/ClassicPress-Design/Logo` as the path for the shortcode.

**Comment by timbocode** [comment]
Yeah, just noticed that. I'll update my own copy.

Have you reworked the `file-list.php` MU plugin or does that still need doing? If you've already done it, that's fine.

I'd started tweaking it to fetch file names from Github which is a bit trickier than doing it locally but I got it sorted using Curl and an authorization token. I used my own fork for testing.

**Comment by timbocode** [comment]
Just noticed you've already done it so that's fine. Good stuff. 👍

**Pull request merged**
