### PR TITLE
Optimised SVG and PNG

### PR DESCRIPTION
**Pull request by mathewcallaghan**
I have gone ahead and started something, the SVG files are optimised and are a  bit smaller than the currently available versions. The creation of the PNG's is done via a script.

### CODE REVIEW

**Comment by nylen** [comment]
Hi @mathewcallaghan, do you mind if I take this and use it as the base structure for the changes we need to make?

**Comment by nylen** [comment]
Also:

>The creation of the PNG's is done via a script.

This would be a good thing to include in a PR

**Comment by mathewcallaghan** [comment]
I closed and deleted it already. The SVG files were the only thing I really worked on. Making them web optimised. The PNG icons were generated automatically. The structure was more a product of the simple scripting.

**Comment by mathewcallaghan** [comment]
I rushed the script and wanted to improve it before adding /sharing  it.

**Comment by nylen** [comment]
I don't understand why you closed this. I'd like to use it as a starting point and keep the GIMP color palette and the basic folder structure.

**Pull request closed without merging**
